import { audia1, benz, bmw320, golf6, passatcc, toyotacamry } from '/public';

export const CAR_DATA = [
	[
		{
			name: 'VW Golf 6',
			price: '37',
			img: golf6,
			model: 'Golf 6',
			mark: 'Volkswagen',
			year: '2008',
			doors: '4/5',
			air: 'Yes',
			transmission: 'Manual',
			fuel: 'Diesel',
		},
	],
	[
		{
			name: 'Audi A1 S-Line',
			price: '45',
			img: audia1,
			model: 'Audi',
			mark: 'A1',
			year: '2012',
			doors: '4/5',
			air: 'Yes',
			transmission: 'Manual',
			fuel: 'Gasoline',
		},
	],
	[
		{
			name: 'Toyota Camry',
			price: '30',
			img: toyotacamry,
			model: 'Camry',
			mark: 'Toyota',
			year: '2006',
			doors: '4/5',
			air: 'Yes',
			transmission: 'Automatic',
			fuel: 'Hybrid',
		},
	],
	[
		{
			name: 'BMW 320 ModernLine',
			price: '35',
			img: bmw320,
			model: '320',
			mark: 'BMW',
			year: '2012',
			doors: '4/5',
			air: 'Yes',
			transmission: 'Manual',
			fuel: 'Diesel',
		},
	],
	[
		{
			name: 'Mercedes-Benz GLK',
			price: '50',
			img: benz,
			model: 'Benz GLK',
			mark: 'Mercedes',
			year: '2006',
			doors: '4/5',
			air: 'Yes',
			transmission: 'Manual',
			fuel: 'Diesel',
		},
	],
	[
		{
			name: 'VW Passat CC',
			price: '25',
			img: passatcc,
			model: 'Passat CC',
			mark: 'Volkswagen',
			year: '2008',
			doors: '4/5',
			air: 'Yes',
			transmission: 'Automatic',
			fuel: 'Gasoline',
		},
	],
];
